In [61]:
# get a metrix and change substitue o with column mean.
import numpy as np
import pandas as pd
random_matrix=np.random.randint(0,10,size=(3,3))
print(random_matrix)
matrix=pd.DataFrame(random_matrix)
print(matrix.sum(axis=1))
for column in matrix.columns:
    value=matrix[column].mean()
    matrix[column]=matrix[column].replace(0,value)
matrix.var(axis=0)    

[[7 0 9]
 [2 4 8]
 [7 2 8]]
0    16
1    14
2    17
dtype: int64


0    8.333333
1    1.333333
2    0.333333
dtype: float64

In [59]:
#sasme task from  the help of random
import random
numbers=[random.randint(10,20) for x in range(9)]
df=pd.array(numbers)



In [60]:
df

<IntegerArray>
[13, 16, 19, 20, 14, 13, 18, 12, 12]
Length: 9, dtype: Int64