In [1]:
import tensorflow as tf
import numpy as np
tf.constant([[1,2,3],[2,3,4],[4,5,6]])
tf.constant(value=1,shape=(4,4),dtype='float32')

2024-11-17 17:26:27.610450: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-11-17 17:26:28.150105: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-17 17:26:28.360211: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-17 17:26:28.418474: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-17 17:26:28.830826: I tensorflow/core/platform/cpu_feature_guar

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [6]:
tdf=tf.random.uniform([3,2])
tdf[1,:]
tf.random.normal([3,4],0,1)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.3606979 ,  0.6303468 ,  1.1268734 ,  0.82979673],
       [-0.8648273 , -0.40672934, -0.37069476,  0.4942842 ],
       [-0.8562077 , -1.0655525 , -0.6461347 ,  0.31998274]],
      dtype=float32)>

In [10]:
#Operations
tdf1=tf.constant([[2,3],[1,2]],shape=(2,2))
tdf2=tf.constant([[1,2],[2,4]],shape=(2,2))
#Addition
result_tf=tf.multiply(tdf1,tdf2)
print(result_tf)
result_tf=tdf1+tdf2
print(result_tf)
#Mat multi
print(tf.matmul(tdf1,tdf2))
#Power
print(tf.pow(tdf1,5))

tf.Tensor(
[[2 6]
 [2 8]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 5]
 [3 6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 8 16]
 [ 5 10]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 32 243]
 [  1  32]], shape=(2, 2), dtype=int32)


In [15]:
#model training with keras
from tensorflow import keras
from tensorflow.keras import datasets
from tensorflow.keras.datasets import mnist
from tensorflow.keras import layers

(x_train,y_train),(x_test,y_test)=mnist.load_data()
print(x_train.shape)
print(x_test.shape)

#reshape the column
x_train=x_train.reshape(-1,28*28).astype('float32')/255.0
x_test=x_test.reshape(-1,28*28).astype('float32')/255.0


(60000, 28, 28)
(10000, 28, 28)


In [23]:
#Sequential API
model= keras.models.Sequential(
    [ keras.Input(shape=(784,)),
    layers.Dense(512,name='First Layer',activation='tanh'),
     layers.Dense(256,name='Second Layer',activation='tanh'),
     layers.Dense(10,name='Output Layer')]
)

model.compile(loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),optimizer=keras.optimizers.Adam(learning_rate=0.001),metrics=['accuracy'])
model.fit(x_train,y_train,batch_size=32,epochs=7,verbose=2)
model.evaluate(x_test,y_test,batch_size=32,verbose=2)
model.summary()

Epoch 1/7
1875/1875 - 5s - 3ms/step - accuracy: 0.9321 - loss: 0.2271
Epoch 2/7
1875/1875 - 3s - 2ms/step - accuracy: 0.9676 - loss: 0.1068
Epoch 3/7
1875/1875 - 3s - 2ms/step - accuracy: 0.9755 - loss: 0.0772
Epoch 4/7
1875/1875 - 6s - 3ms/step - accuracy: 0.9823 - loss: 0.0569
Epoch 5/7
1875/1875 - 8s - 4ms/step - accuracy: 0.9854 - loss: 0.0476
Epoch 6/7
1875/1875 - 8s - 4ms/step - accuracy: 0.9875 - loss: 0.0379
Epoch 7/7
1875/1875 - 4s - 2ms/step - accuracy: 0.9890 - loss: 0.0337
313/313 - 1s - 2ms/step - accuracy: 0.9753 - loss: 0.0849


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ layer-1 (Dense)                 │ (None, 512)            │       401,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer-2 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,607,456 (6.13 MB)

 Trainable params: 535,818 (2.04 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,071,638 (4.09 MB)

In [13]:
#Functional API (Flexible)
a0=keras.Input(shape=(784,))
a1=layers.Dense(512,activation='relu')(a0)
a2=layers.Dense(256,activation='relu')(a1)
output=layers.Dense(10,name='output',activation='softmax')(a2)
model=keras.Model(inputs=a0,outputs=output)


model.compile(loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),optimizer=keras.optimizers.Adam(learning_rate=0.001),metrics=['accuracy'])
model.fit(x_train,y_train,batch_size=32,epochs=7,verbose=2)
model.summary()
model.evaluate(x_test,y_test,batch_size=32,verbose=2)

Epoch 1/7
1875/1875 - 3s - 2ms/step - accuracy: 0.9434 - loss: 0.1854
Epoch 2/7
1875/1875 - 2s - 1ms/step - accuracy: 0.9759 - loss: 0.0776
Epoch 3/7
1875/1875 - 2s - 1ms/step - accuracy: 0.9820 - loss: 0.0553
Epoch 4/7
1875/1875 - 2s - 1ms/step - accuracy: 0.9869 - loss: 0.0410
Epoch 5/7
1875/1875 - 2s - 1ms/step - accuracy: 0.9898 - loss: 0.0323
Epoch 6/7
1875/1875 - 2s - 1ms/step - accuracy: 0.9908 - loss: 0.0293
Epoch 7/7
1875/1875 - 2s - 1ms/step - accuracy: 0.9925 - loss: 0.0227


Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_9 (InputLayer)      │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 512)            │       401,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,607,456 (6.13 MB)

 Trainable params: 535,818 (2.04 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,071,638 (4.09 MB)

In [20]:
test=x_test[:3]
print(test)
result=model.predict(test)
result

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step


array([[-10.037038  ,  -4.781556  ,  -9.285779  ,  -3.0802646 ,
        -11.509281  , -10.915493  , -21.237877  ,  17.091265  ,
        -14.732452  ,   1.0195824 ],
       [-13.322335  ,  -2.153508  ,  20.084236  ,  -4.5078816 ,
        -15.481971  , -12.632195  ,  -6.1705685 ,  -9.612949  ,
         -0.3353736 , -19.26257   ],
       [-12.307164  ,  14.114236  ,  -7.395856  , -12.230837  ,
         -0.94303375,  -7.871043  ,  -2.5777814 ,  -1.4372414 ,
         -0.40331838,  -8.53709   ]], dtype=float32)